### PR TITLE
feat(tiflash): upgrade to LLVM17 & remove useless prepare tool stage

### PR DESCRIPTION
**Pull request by Lloyd-Pottiger**
```shell
$ docker run -it --rm  hub.pingcap.net/tiflash/tiflash-llvm-base:amd64-llvm-17.0.6 /bin/bash
[root@d7d2c6310768 root]# which clang-format
/usr/local/bin/clang-format
[root@d7d2c6310768 root]# which clang-tidy  
/usr/local/bin/clang-tidy
[root@d7d2c6310768 root]# clang-tidy --version
LLVM (http://llvm.org/):
  LLVM version 17.0.6
  Optimized build.
[root@d7d2c6310768 root]# clang-format --version
clang-format version 17.0.6 (/llvm-project/clang 6009708b4367171ccdbf4b5905cb6a803753fe18)
[root@d7d2c6310768 root]# which ccahe
/usr/bin/which: no ccahe in (/root//.cargo/bin:/opt/cmake/bin:/usr/local/bin/:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/root/.cargo/bin)
[root@d7d2c6310768 root]# which ccache
/usr/local/bin/ccache
[root@d7d2c6310768 root]# ccache --version
ccache version 4.5.1
Features: file-storage http-storage redis-storage

Copyright (C) 2002-2007 Andrew Tridgell
Copyright (C) 2009-2021 Joel Rosdahl and other contributors

See <https://ccache.dev/credits.html> for a complete list of contributors.

This program is free software; you can redistribute it and/or modify it under
the terms of the GNU General Public License as published by the Free Software
Foundation; either version 3 of the License, or (at your option) any later
version.
[root@d7d2c6310768 root]# cmake --version
cmake version 3.24.2

CMake suite maintained and supported by Kitware (kitware.com/cmake).
[root@d7d2c6310768 root]# gcovr --version
bash: gcovr: command not found
[root@d7d2c6310768 root]# gcov --version
gcov (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or 
FITNESS FOR A PARTICULAR PURPOSE.

```

The image has contained all necessary tools.

### CODE REVIEW

**Review by purelind — APPROVED** [review]
/lgtm

**Review by JaySon-Huang — APPROVED** [review]
LGTM

**Pull request merged**
