### PR TITLE
feat(tiflow): support skip ci if only change docs

### PR DESCRIPTION
**Pull request by purelind**
support skip ci if only change docs.

Test passed  https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftiflow%2Fpull_cdc_integration_test/detail/pull_cdc_integration_test/47/pipeline/

image

### CODE REVIEW

**Review by CharlesCheung96 — APPROVED** [review]

**Comment by wuhuizuo** [comment]
why not skip the triggering when only change docs?

**Pull request closed without merging**
