### PR TITLE
add  extra package for version < 6.0

### PR DESCRIPTION
**Pull request by lijie0123**

### CODE REVIEW

**Review by wuhuizuo — APPROVED** [review]

**Comment by purelind** [comment]
what is the difference between `libs.release_dm_ansible_amd64(dm_sha1, RELEASE_TAG)` and this pipeline https://cd.pingcap.net/job/tiup-package-offline-mirror-dm/

**Comment by purelind** [comment]
packages example upload by `libs.release_dm_ansible_amd64(dm_sha1, RELEASE_TAG)`
* https://download.pingcap.org/dm-v5.4.1-linux-amd64.tar.gz
* https://download.pingcap.org/dm-ansible-v5.4.1.tar.gz

upload by pipeline https://cd.pingcap.net/job/tiup-package-offline-mirror-dm/
* https://download.pingcap.org/tidb-dm-v5.4.1-linux-amd64.tar.gz

**Pull request merged**
