### PR TITLE
docs: bump pdf stable version to release-8.1

### PR DESCRIPTION
**Pull request by Oreoxmt**
Update the stable PDF version of TiDB and TiDB Cloud:

- TiDB: the stable PDF version is updated from release-7.5 to release-8.1.
- TiDB Cloud: the stable PDF version will remain at release-7.5 to ensure consistency with the current TiDB Cloud documentation.

### CODE REVIEW

**Review by Yuiham — APPROVED** [review]

**Comment by Oreoxmt** [comment]
@purelind @wuhuizuo Please help review and merge this PR

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
