### PR TITLE
[Update] boost integration test script

### PR DESCRIPTION
**Pull request by Icemap**

### CODE REVIEW

**Comment by Icemap** [comment]
Replay test:
- https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_integration_test/detail/tidb_test_ghpr_integration_test/1508/pipeline/88

Scripts:
- https://gist.githubusercontent.com/Icemap/290b63f2345861ed3db6ffbae60cf70e/raw/57b4a8f5f88a50269401bd1070be4ca854f19cfa/integration_prepare.sh
- https://gist.githubusercontent.com/Icemap/31184b20284a5fb216bebcb7c5449aca/raw/74b19624dc808ea90a49f760913bb688bfe701e7/integration_test.sh

Related:
https://github.com/PingCAP-QE/ci/pull/1289

**Comment by Icemap** [comment]
Test PR: https://github.com/pingcap/tidb-test/pull/1969

**Review by wuhuizuo — APPROVED** [review]
/merge

**Pull request merged**
