### PR TITLE
dm: add minio for s3 test

### PR DESCRIPTION
**Pull request by WizardXiao**
as title.

### CODE REVIEW

**Review by purelind — APPROVED** [review]
lgtm

**Review by Ehco1996 — APPROVED** [review]

**Comment by Ehco1996** [comment]
@WizardXiao  can you provide a relay url to let us check if this change will affects current CI ?

**Comment by Ehco1996** [comment]
@purelind  please merge 🏄

**Comment by WizardXiao** [comment]
> @WizardXiao can you provide a relay url to let us check if this change will affects current CI ?

ok, this change will not affect current CI, we will check `minio` before run integration tests. 
https://ci2.pingcap.net/job/dm_ghpr_compatibility_test/2365/
https://ci2.pingcap.net/job/dm_ghpr_integration_test/3167
ps. there has other integration test error, but it has nothing to do with this change.

**Pull request merged**
