### PR TITLE
Change Base image to pingcap/alpine-glibc:alpine-3.14.3-gcompat for ARM64

### PR DESCRIPTION
**Pull request by n0vad3v**
This PR aims to change all base image for ARM64 from `centos:8` to `pingcap/alpine-glibc:alpine-3.14.3-gcompat`.

### CODE REVIEW

**Comment by n0vad3v** [comment]
Do not merge as tests are needed.

**Comment by wuhuizuo** [comment]
current base image was rocky linux 9.0

**Pull request closed without merging**
