### PR TITLE
feat(tiflash): start use rocky8 as base image

### PR DESCRIPTION
**Pull request by purelind**
CentOS 7 has reached the end of its life cycle. Starting from version 8.4, we began using Rocky Linux 8 as the base image.

Relate to https://github.com/pingcap/tiflash/pull/9556

### CODE REVIEW

**Comment by purelind** [comment]
integration test retest link  https://do.pingcap.net/jenkins/job/pingcap/job/tiflash/job/pull_integration_test/1829/

unit test retest link  https://do.pingcap.net/jenkins/job/pingcap/job/tiflash/job/pull_unit_test/1878/

**Review by Lloyd-Pottiger — APPROVED** [review]
lgtm

**Pull request merged**
