### PR TITLE
feat: optimize upload cache of tikv ut

### PR DESCRIPTION
**Pull request by purelind**
Close https://github.com/PingCAP-QE/ci/issues/2193
## Why
The existing upload requires asynchronous uploading of each UT test binary, which may result in some caches not being successfully uploaded. This will affect the subsequent testing.

## How
After optimization, we pack all the ut test binary files that need to be uploaded together and upload them to ks3. At the same time, we only use ks3util for uploading and downloading operations. This not only improves the stability of uploads but also reduces the time required for uploading and downloading.
Upload time before optimization: 50s
Upload time after optimization: 22s

### CODE REVIEW

**Comment by purelind** [comment]
Test passed
1. ut with nexttest https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/39920/pipeline/10/
2. ut legacy  https://ci.pingcap.net/blue/organizations/jenkins/tikv_ghpr_test/detail/tikv_ghpr_test/39925/pipeline/

**Review by glorv — COMMENTED** [review]
LGTM

**Pull request merged**
