### PR TITLE
feat(tiflow): split tiflow storage test on v7.1.0

### PR DESCRIPTION
**Pull request by purelind**
split tiflow storage test on v7.1.0.

### CODE REVIEW

**Comment by purelind** [comment]
Sadly to exclude strings containing 'v7.1.0', i will need to use a negative lookahead. Unfortunately, Go's standard regular expression package regexp does not support negative lookahead. I'll think about how to handle it again.

**Review by wuhuizuo — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
