### PR TITLE
feat: switch to use new pipeline trigger by prow in branch 7.1

### PR DESCRIPTION
**Pull request by purelind**
Swtich to use new pipeline trigger by prow in tikv & tiflash branch release-7.1

### CODE REVIEW

**Comment by purelind** [comment]
## tiflash
image
image
## tikv
image

**Review by glorv — APPROVED** [review]

**Review by Lloyd-Pottiger — APPROVED** [review]

**Review by zanmato1984 — APPROVED** [review]

**Review by JaySon-Huang — APPROVED** [review]

**Pull request merged**
