### PR TITLE
use new sync_diff

### PR DESCRIPTION
**Pull request by Leavrth**
revert #456

### CODE REVIEW

**Review by lichunzhu — APPROVED** [review]

**Comment by Leavrth** [comment]
CI pass

1. [dm-integration-test](https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_integration_test_copy/detail/dm_ghpr_integration_test_copy/32/pipeline/)
2. [dm-compatibility-test](https://ci2.pingcap.net/blue/organizations/jenkins/dm_ghpr_compatibility_test_copy/detail/dm_ghpr_compatibility_test_copy/7/pipeline/)
3. [cdc-kafka-integration-test](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy_new_sync_diff/detail/cdc_ghpr_integration_test_copy_new_sync_diff/24/pipeline/115/)
4. [cdc-integration-test](https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy_new_sync_diff/detail/cdc_ghpr_integration_test_copy_new_sync_diff/25/pipeline/)

**Review by zhouqiang-cl — APPROVED** [review]
LGTM

**Pull request merged**
