### PR TITLE
feat(tidb): enable trigger for tidb pull-integration-e2e-test

### PR DESCRIPTION
**Pull request by purelind**
Enable trigger for tidb pull-integration-e2e-test.

### CODE REVIEW

**Comment by purelind** [comment]
The test has been running stably for three weeks. Check the link https://prow.tidb.net/?repo=pingcap%2Ftidb&type=postsubmit&job=pingcap%2Ftidb%2Fmerged_integration_e2e_test
image

**Comment by purelind** [comment]
/hold

wait for review

**Comment by purelind** [comment]
/unhold 

Already communicated and confirmed with the owner.

**Review by bb7133 — COMMENTED** [review]
LGTM

**Pull request merged**
