### PR TITLE
*: add 74 test files to msyql-test on master in whitelist mode 

### PR DESCRIPTION
**Pull request by zimulala**
Add 77 test files to the whitelist as follows:
`
bug28940878 bug33509 bug46760 delete_myisam ds_mrr-big error_simulation filesort_json filter_single_col_idx_big func_compress func_date_add_myisam func_default func_math func_str_myisam grant_explain_non_select grant_lowercase_fs histogram_singleton implicit_char_to_num_conversion index_merge_bug29952775 innodb_tmp_table_heap_to_disk insert_select_myisam join_crash keywords lead_lag lead_lag_explain limit limit_myisam long_tmpdir lowercase_fs_off lowercase_mixed_tmpdir lowercase_table2 lowercase_table4 lowercase_table5 lowercase_utf8 lowercase_view lpad metadata multi_update_innodb multi_update_tiny_hash null_key_all_innodb odbc opt_hints opt_hints_join_order opt_hints_subquery optimizer_bug12837084 order_by_limit overflow packet_myisam parser parser_precedence partition_locking_ps_protocol reset_connection roles-ddl roles-view roles_bugs_wildcard 
 show_check_cs_myisam show_profile show_variables strict strict_autoinc_2innodb subquery_antijoin subquery_bugs subquery_sj_innodb_all sum_distinct-big type_timestamp_myisam update_myisam user_if_exists varbinary variables_dynamic_privs view_grant view_myisam warnings window_functions_bugs window_functions_interesting_orders
`

### CODE REVIEW

**Comment by zimulala** [comment]
PTAL @purelind @bb7133

**Comment by purelind** [comment]
replay a passed ci, found some failed tests https://ci.pingcap.net/blue/organizations/jenkins/tidb_ghpr_mysql_test/detail/tidb_ghpr_mysql_test/10174/pipeline/

**Comment by zimulala** [comment]
@purelind 
Excuse me, `role` and `variables` are not added to this PR. They are already there

**Comment by zimulala** [comment]
It passed the CI
https://ci.pingcap.net/job/tidb_test_ghpr_mysql_test/1416/
https://ci.pingcap.net/blue/organizations/jenkins/tidb_test_ghpr_mysql_test/detail/tidb_test_ghpr_mysql_test/1416/pipeline/76/
@purelind

**Review by purelind — APPROVED** [review]

**Pull request merged**
