### PR TITLE
fix(tidb): fix script integrationtest.sh

### PR DESCRIPTION
**Pull request by purelind**
* Correct start pd cmd params.
* Specify using store tikv for testing.

### CODE REVIEW

**Comment by purelind** [comment]
Currently, running with store tikv will result in the following errors.
```shell
ERRO[0663] 8 tests failed
ERRO[0663] run test [executor/admin] err: sql:admin checksum table cache_admin_table_with_index_test;: failed to run query
"admin checksum table cache_admin_table_with_index_test;"
 around line 66,
we need(172):
admin checksum table cache_admin_table_with_index_test;
Db_name Table_name      Checksum_crc64_xor      Total_kvs       Total_bytes
executor__admin cache_admin_table_with_index_test       0       2       2

but got(172):
admin checksum table cache_admin_table_with_index_test;
Db_name Table_name      Checksum_crc64_xor      Total_kvs       Total_bytes
executor__admin cache_admin_table_with_index_test       0       0       0

ERRO[0663] run test [executor/executor] err: sql:change pump to node_state ='paused' for node_id 'pump1';: failed to run query
"change pump to node_state ='paused' for node_id 'pump1';"
 around line 693,
we need(132):
change pump to node_state ='paused' for node_id 'pump1';
Error 1105 (HY000): URL scheme must be http, https, unix, or unixs:
change
but got(132):
change pump to node_state ='paused' for node_id 'pump1';
Error 1105 (HY000): node pump, id pump1 from etcd 127.0.0.1:2379 not found

ERRO[0663] run test [expression/builtin] err: sql:select * from tb5 where cast(a as unsigned int)=0;: failed to run query
"select * from tb5 where cast(a as unsigned int)=0;"
 around line 280,
we need(156):
select * from tb5 where cast(a as unsigned int)=0;
a       b
Level   Code    Message
Warning 1690    constant 1.844674407370955e+20 overflows bigint
select * from tb5 whe
but got(156):
select * from tb5 where cast(a as unsigned int)=0;
a       b
Level   Code    Message
Warning 1690    evaluation failed: constant 184467440737095500000 overflows LongLong

ERRO[0663] run test [expression/charset_and_collation] err: sql:admin recover index t a;: run "admin recover index t a;" at line 359 err Error 1105 (HY000): [components/tidb_query_executors/src/table_scan_executor.rs:425]: Data is corrupted, missing data for NOT NULL column (offset = 0)
ERRO[0663] run test [expression/issues] err: sql:select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;: failed to run query
"select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;"
 around line 1445,
we need(79):
select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;
a       b
sele
but got(79):
select * from t where field('A', a collate utf8mb4_general_ci, b) > 1;
a       b
a       A
ERRO[0663] run test [planner/cascades/integration] err: sql:select /*+ HASH_AGG() */ a, count(distinct a) from t;: failed to run query
"select /*+ HASH_AGG() */ a, count(distinct a) from t;"
 around line 135,
we need(78):
select /*+ HASH_AGG() */ a, count(distinct a) from t;
a       count(distinct a)
1       2

but got(78):
select /*+ HASH_AGG() */ a, count(distinct a) from t;
a       count(distinct a)
2       2

ERRO[0663] run test [planner/core/plan_cache] err: sql:select * from IDT_20290 where col2 * 049015787697063065230692384394107598316198958.1850509 >= 659971401668884663953087553591534913868320924.5040396 and col2 = 869042976700631943559871054704914143535627349.9659934;: failed to run query
"select * from IDT_20290 where col2 * 049015787697063065230692384394107598316198958.1850509 >= 659971401668884663953087553591534913868320924.5040396 and col2 = 869042976700631943559871054704914143535627349.9659934;"
 around line 209,
we need(263):
select * from IDT_20290 where col2 * 049015787697063065230692384394107598316198958.1850509 >= 659971401668884663953087553591534913868320924.5040396 and col2 = 869042976700631943559871054704914143535627349.9659934;
Error 1690 (22003): DECIMAL value is out of range
but got(263):
select * from IDT_20290 where col2 * 049015787697063065230692384394107598316198958.1850509 >= 659971401668884663953087553591534913868320924.5040396 and col2 = 869042976700631943559871054704914143535627349.9659934;
Error 1690 (22003):  value is out of range in ''
ERRO[0663] run test [session/vars] err: sql:SELECT variable_value FROM mysql.tidb WHERE variable_name = 'tikv_gc_enable';: failed to run query
"SELECT variable_value FROM mysql.tidb WHERE variable_name = 'tikv_gc_enable';"
 around line 3,
we need(98):
SELECT variable_value FROM mysql.tidb WHERE variable_name = 'tikv_gc_enable';
variable_value
SET G
but got(98):
SELECT variable_value FROM mysql.tidb WHERE variable_name = 'tikv_gc_enable';
variable_value
true
```

**Review by Defined2014 — APPROVED** [review]
https://github.com/pingcap/tidb/pull/47697 fixed all problems for real TiKV, I think this PR could merge now.

**Review by Defined2014 — APPROVED** [review]
LGTM

**Pull request merged**
