### PR TITLE
Update tiflash-sanitizer-daily.groovy to add rust code cache

### PR DESCRIPTION
**Pull request by solotzg**
Verified in https://ci.pingcap.net/blue/organizations/jenkins/tiflash-sanitizer-daily/detail/tiflash-sanitizer-daily/638/pipeline

### CODE REVIEW

**Comment by solotzg** [comment]
@purelind PTAL

**Review by purelind — APPROVED** [review]
LGTM

**Comment by wuhuizuo** [comment]
nit: Commit message should not be too common 🤝 .
@solotzg

**Comment by solotzg** [comment]
> nit: Commit message should not be too common 🤝 . @solotzg

@wuhuizuo  Can we use the PR title as commit message automatically?

**Pull request merged**
