### PR TITLE
install gtests_dbms by cmake

### PR DESCRIPTION
**Pull request by lidezhu**
Install `gtests_dbms` by cmake install rule.

### CODE REVIEW

**Comment by wuhuizuo** [comment]
@purelind please review it.
@lidezhu please add replay links with those changes.

**Comment by lidezhu** [comment]
> @purelind please review it. @lidezhu please add replay links with those changes.

Is there any documentation about how to get the replay link?

**Comment by purelind** [comment]
> > @purelind please review it. @lidezhu please add replay links with those changes.
> 
> Is there any documentation about how to get the replay link?

Find a pipeline that has been executed successfully, click the replay button, and paste the modified groovy script to test it

**Comment by lidezhu** [comment]
https://ci.pingcap.net/job/tiflash-build-common/14584/

**Review by purelind — APPROVED** [review]
lgtm

**Pull request merged**
