### PR TITLE
refactor(pipelines/tikv/pd): simplfy git repo cache keys and checkout peer repos with `component.checkout`

### PR DESCRIPTION
**Pull request by wuhuizuo**
Just copy the refactoring to all prow style pipelines
- Ref:  #2113

### CODE REVIEW

**Review by purelind — CHANGES_REQUESTED** [review]
Please split multiple PRs for modification so many files.

**Comment by wuhuizuo** [comment]
tested in: https://do.pingcap.net/jenkins/blue/organizations/jenkins/tikv%2Fpd%2Fpull_integration_copr_test/detail/pull_integration_copr_test/10/pipeline

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
