### PR TITLE
tidb: update golangci-lint version on master / release-5.x

### PR DESCRIPTION
**Pull request by purelind**
golangci-lint version need upgrade from v1.21.0 to v1.29.0 on master&release-5.x

### CODE REVIEW

**Comment by purelind** [comment]
hold

**Comment by purelind** [comment]
hold on until tidb lint releated pr merged  [25389](https://github.com/pingcap/tidb/pull/25389)

**Comment by JaySon-Huang** [comment]
The golangci-lint has been upgraded to v1.41.1 on master by this PR: https://github.com/pingcap/tidb/pull/25912
And those lint has been fixed.

**Comment by purelind** [comment]
fix lint errors on release-5.1  #https://github.com/pingcap/tidb/pull/26295

**Pull request merged**
