### PR TITLE
jenkins/pipeline/cd: make curl exit with err code

### PR DESCRIPTION
**Pull request by wuhuizuo**
curl default always exit with zero code.
add `--fail` option to `curl` cmd for file uploading.

### CODE REVIEW

**Comment by wuhuizuo** [comment]
@purelind pls review it

**Comment by purelind** [comment]
--fail : Fail silently (no output at all) on HTTP errors (H)
Have you misunderstood its meaning?

**Review by purelind — CHANGES_REQUESTED** [review]
--fail: Fail silently (no output at all) on HTTP errors (H)
not means  exit with an error code.

**Comment by wuhuizuo** [comment]
> --fail: Fail silently (no output at all) on HTTP errors (H) not means exit with an error code.

pls see: 
image

**Comment by wuhuizuo** [comment]
new pipeline test passed (by  manually replay) @purelind

**Comment by wuhuizuo** [comment]
The `fileserver` will be replaced with a more standard artifact server in this year.

the `fileserver` is not RESTFul and cloud native, and I can not fix and rollout it online, current the best way is update the `cd` pipelines.

**Pull request merged**
