### PR TITLE
add dm ghpr test

### PR DESCRIPTION
**Pull request by Ehco1996**
add dm it and ut test

### CODE REVIEW

**Comment by zhouqiang-cl** [comment]
LGTM

**Comment by Ehco1996** [comment]
@zhouqiang-cl  this pr is ready.

**Comment by Ehco1996** [comment]
this pr is ready~

**Comment by lance6716** [comment]
how about update go version to 1.16, so we could fix https://github.com/pingcap/dm/pull/1698

**Comment by Ehco1996** [comment]
> how about updating go version to 1.16 in this PR, so we could fix [pingcap/dm#1698](https://github.com/pingcap/dm/pull/1698)

sounds great , i will update ci go envrionment to go.1.16 after [pingcap/dm#1698](https://github.com/pingcap/dm/pull/1698) closed

/hold

**Pull request closed without merging**
