### PR TITLE
add building bench_dbms to tiflash ci pipeline

### PR DESCRIPTION
**Pull request by guo-shaoge**

### CODE REVIEW

**Comment by guo-shaoge** [comment]
wait for https://github.com/pingcap/tiflash/pull/8194

**Comment by purelind** [comment]
replay test passed  https://ci.pingcap.net/blue/organizations/jenkins/tiflash-build-common/detail/tiflash-build-common/30799/pipeline/166

**Review by purelind — APPROVED** [review]
/lgtm

**Pull request merged**
