### PR TITLE
fix(pipelines/pingcap/tidb): fix coverage data path and refactor unit job

### PR DESCRIPTION
**Pull request by wuhuizuo**
Ref:
- #2171

### CODE REVIEW

**Comment by wuhuizuo** [comment]
tested in:
- https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_unit_test/detail/ghpr_unit_test/28535/pipeline/
- https://do.pingcap.net/jenkins/blue/organizations/jenkins/pingcap%2Ftidb%2Fghpr_check2/detail/ghpr_check2/24746/pipeline/

**Review by purelind — APPROVED** [review]
/lgtm

**Comment by wuhuizuo** [comment]
/unhold

tests are passed

**Pull request merged**
