### PR TITLE
build: add cdc binary upload path on multi-branch build

### PR DESCRIPTION
**Pull request by purelind**
In order to be compatible with the BR integration test pipeline, we need to upload the CDC binary to path like `builds/pingcap/ticdc/${githash}/centos7/ticdc-linux-amd64.tar.gz`.

download cdc binary in [br pipeline](https://github.com/PingCAP-QE/ci/blob/main/jenkins/pipelines/ci/br/br_ghpr_unit_and_integration_test.groovy#L424-L426)
image

### CODE REVIEW

**Comment by purelind** [comment]
replay test  https://cd.pingcap.net/blue/organizations/jenkins/build_cdc_multi_branch/detail/release-6.1/150/pipeline

**Review by lijie0123 — APPROVED** [review]

**Pull request merged**
