### PR TITLE
Add github actions for pr and push to main

### PR DESCRIPTION
**Pull request by AsterNighT**

### CODE REVIEW

**Comment by AsterNighT** [comment]
The action file is almost ready. The jobs are expected to fail for the code and the tests. @lilinghai PTAL.

**Comment by lilinghai** [comment]
I think it's necessary to satisfy the requirement of the `go-lint` through modifying our code.

**Comment by AsterNighT** [comment]
@lilinghai PTAL

**Review by lilinghai — APPROVED** [review]
lgtm

**Pull request merged**
