### PR TITLE
ticdc: Use the corresponding version

### PR DESCRIPTION
**Pull request by hi-rustin**
Release-5.1 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/17/pipeline/110

Release-5.2 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/19/pipeline/109 

Release-5.0 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/20/pipeline/101

Release-4.0 https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/22/pipeline/101

Master https://ci2.pingcap.net/blue/organizations/jenkins/cdc_ghpr_integration_test_copy/detail/cdc_ghpr_integration_test_copy/23/pipeline/101

### CODE REVIEW

**Comment by hi-rustin** [comment]
cc: @amyangfei @purelind Could you please take a look? Thanks!

**Comment by hi-rustin** [comment]
/hold

- [ ] Better code

**Review by amyangfei — APPROVED** [review]

**Comment by hi-rustin** [comment]
/unhold

Ready to merge.

**Review by purelind — APPROVED** [review]
LGTM

**Pull request merged**
