### PR TITLE
revert sanitizer modify in #1142

### PR DESCRIPTION
**Pull request by hehechen**
Reverts sanitizer modify in PingCAP-QE/ci#1142 for [TiFlash sanitizer CI failure](https://ci.pingcap.net/job/tiflash-sanitizer-daily/350/console).

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
LGTM

**Comment by hehechen** [comment]
https://ci.pingcap.net/job/tiflash-sanitizer-daily/353/console  build successfully in replay.

**Review by wuhuizuo — APPROVED** [review]
/lgtm

**Pull request merged**
